const imageMap = {
'Acerbatus': '../images/acerbatus.webp',
'Alchemy Whip': '../images/alchemy_whip.webp',
'Alucard Shield': './images/alucard_shield.webp',
'Alucard Spear': './images/alucard_spear.webp',
'Alucard Swords': './images/alucard_swords.webp',
'Alucart Sworb': './images/alucart_sworb.webp',
'Armor': './images/armor.webp',
'Ashes of Muspell': 'images/ashes_of_muspell.webp',
'Atmo-Torpedo': 'images/atmo_torpedo.webp',
'Attractorb': 'images/attractorb.webp',
'Aurablaster Tip': 'images/aurablaster_tip.webp',
'Axe': 'images/axe.webp',
'BFC2000-AD': 'images/BFC2000-AD.webp',
'Bi-Bracelet': 'images/bi-bracelet.webp',
'Big Fuzzy Fist': 'images/big_fuzzy_fist.webp',
'Blade Crossbow': 'images/blade_crossbow.webp',
'Bloody Tear': 'images/bloody_tear.webp',
'Boo Roo Boolle': 'images/boo_roo_boolle.webp',
'Bracelet': 'images/bracelet.webp',
'Bracer': 'images/bracer.webp',
'Bwaka Knife': 'images/bwaka_knife.webp',
'C-U-Laser': 'images/C-U-laser.webp',
'Candelabrador': 'images/candelabrador.webp',
'Celestial Voulge': 'images/celestial_voulge.webp',
'Clear Asteroids': 'images/clear_asteroids.webp',
'Clear Debris': 'images/clear_debris.webp',
'Clock Lancet': 'images/clock_lancet.webp',
'Clock Tower': 'images/clock_tower.webp',
'Clover': 'images/clover.webp',
'Cocytus': 'images/cocytus.webp',
'Confodere': 'images/confodere.webp',
'Crimson Shroud': 'images/crimson_shroud.webp',
'Crissaegrim Tip': 'images/crissaegrim_tip.webp',
'Cross Crasher Tip': 'images/cross_crasher_tip.webp',
'Cross': 'images/cross.webp',
'Crossed Wires': 'images/crossed_wires.webp',
'Crown': 'images/crown.webp',
'Curved Knife': 'images/curved_knife.webp',
'Dark Iron Shield': 'images/dark_iron_shield.webp',
'Daybreaker Tip': 'images/daybreaker_tip.webp',
'Death Spiral': 'images/death_spiral.webp',
'Discus': 'images/discus.webp',
'Diver Mines': 'images/diver_mines.webp',
'Dragon Water Whip': 'images/dragon_water_whip.webp',
'Duplicator': 'images/duplicator.webp',
'Ebony Wings': 'images/ebony_wings.webp',
'Echo Night': 'images/echo_night.webp',
'Eight The Sparrow': 'images/eight_the_sparrow.webp',
'Emergency Meeting': 'images/emergency_meeting.webp',
'Empty Tome': 'images/empty_tome.webp',
'Endo Gears': 'images/endo_gears.webp',
'Epi Head': 'images/epi_head.webp',
'Eskizzibur': 'images/eskizzibur.webp',
'Festive Winds': 'images/festive_winds.webp',
'Fire Wand': 'images/fire_wand.webp',
'Fire-L3GS': 'images/fire-L3GS.webp',
'Firearm': 'images/firearm.webp',
'Flames of Misspell': 'images/flames_of_misspell.webp',
'Flash Arrow': 'images/flash_arrow.webp',
'Four Seasons': 'images/four_seasons.webp',
'Fulgur': 'images/fulgur.webp',
'Fuwalafuwaloo': 'images/fuwalafuwaloo.webp',
'Gale Force': 'images/gale_force.webp',
'Garlic': 'images/garlic.webp',
'Gatti Amari': 'images/gatti_amari.webp',
'Gemma Torpor': 'images/gemma_torpor.webp',
'Glass Fandango': 'images/glass_fandango.webp',
'Globus': 'images/globus.webp',
'Godai Shuffle': 'images/godai_shuffle.webp',
'Gold Ring': 'images/gold_ring.webp',
'Gorgeous Moon': 'images/gorgeous_moon.webp',
"Guardian's Targe": 'images/guardians_targe.webp',
'Gungnir-Souris': 'images/gungnir_souris.webp',
'Hand Grenade': 'images/hand_grenade.webp',
'Heaven Sword': 'images/heaven_sword.webp',
'Hellfire': 'images/hellfire.webp',
'Hex': 'images/hex.webp',
'Hollow Heart': 'images/hollow_heart.webp',
'Holy Wand': 'images/holy_wand.webp',
'Homing Miss': 'images/homing_miss.webp',
'Hydrostormer Tip': 'images/hydrostormer_tip.webp',
'Ice Fang': 'images/ice_fang.webp',
'Impostongue': 'images/impostongue.webp',
'Infinite Corridor': 'images/infinite_corridor.webp',
'Iron Ball': 'images/iron_ball.webp',
'Iron Shield': 'images/iron_shield.webp',
'Javelin': 'images/javelin.webp',
'Jet Black Whip': 'images/jet_black_whip.webp',
"J'Odore": 'images/jodore.webp',
'Just Vent': 'images/just_vent.webp',
"Karoma's Mana": 'images/karomas_mana.webp',
'Keremet Bubbles': 'images/keremet_bubbles.webp',
'Keremet Morbus': 'images/keremet_morbus.webp',
'King Bible': 'images/king_bible.webp',
'Knife': 'images/knife.webp',
'La Borra': 'images/la_borra.webp',
'Laurel': 'images/laurel.webp',
'Legionnaire': 'images/legionnaire.webp',
'Lifesign Scan': 'images/lifesign_scan.webp',
'Lightning Ring': 'images/lightning_ring.webp',
'Long Gun': 'images/long_gun.webp',
'Long Inus': 'images/long_inus.webp',
'Lucky Swipe': 'images/lucky_swipe.webp',
'Luminaire': 'images/luminaire.webp',
'Luminatio': 'images/luminatio.webp',
'Mace': 'images/mace.webp',
'Magic Wand': 'images/magic_wand.webp',
'Mannajja': 'images/mannajja.webp',
'Mazo Familiar': 'images/mazo_familiar.webp',
'Meal Ticket': 'images/meal_ticket.webp',
'Melio Confodere': 'images/melio_confodere.webp',
'Metaglio Left': 'images/metaglio_left.webp',
'Metaglio Right': 'images/metaglio_right.webp',
'Metal Claw': 'images/metal_claw.webp',
'Mille Bolle Blu': 'images/mille_bolle_blu.webp',
'Millionaire': 'images/millionaire.webp',
'Mini Crewmate': 'images/mini_crewmate.webp',
'Mini Engineer': 'images/mini_engineer.webp',
'Mini Ghost': 'images/mini_ghost.webp',
'Mini Guardian': 'images/mini_guardian.webp',
'Mini Impostor': 'images/mini_impostor.webp',
'Mini Scientist': 'images/mini_scientist.webp',
'Mini Shapeshifter': 'images/mini_shapeshifter.webp',
'Mirage Robe': 'images/mirage_robe.webp',
'Moon Rod': 'images/moon_rod.webp',
'Mormegil Tip': 'images/mormegil_tip.webp',
'Multistage Missiles': 'images/multistage_missiles.webp',
'Muramasa': 'images/muramasa.webp',
'Myo Lift': 'images/myo_lift.webp',
'Night Sword': 'images/night_sword.webp',
'Nightmare': 'images/nightmare.webp',
'Nitesco': 'images/nitesco.webp',
'NO FUTURE': 'images/no_future.webp',
'Ophion': 'images/ophion.webp',
'Optical Shot': 'images/optical_shot.webp',
'Pako Battiliar': 'images/pako_battiliar.webp',
'Paranormal Scan': 'images/paranormal_scan.webp',
'Parm Aegis': 'images/parm_aegis.webp',
'Peachone': 'images/peachone.webp',
'Pentagram': 'images/pentagram.webp',
'Peri Pendulum': 'images/peri_pendulum.webp',
'Phas3r': 'images/phas3r.webp',
'Phiera Der Tuphello': 'images/phiera_der_tuphello.webp',
'Phieraggi': 'images/phieraggi.webp',
'Photonstorm': 'images/photonstorm.webp',
'Platinum Whip': 'images/platinum_whip.webp',
'Pneuma Tempestas': 'images/pneuma_tempestas.webp',
'Prism Lass': 'images/prism_lass.webp',
'Prismatic Missile': 'images/prismatic_missile.webp',
'Pronto Beam': 'images/pronto_beam.webp',
'Prototype A': 'images/prototype_A.webp',
'Prototype B': 'images/prototype_B.webp',
'Prototype C': 'images/prototype_C.webp',
'Pummarola': 'images/pummarola.webp',
'Raging Fire': 'images/raging_fire.webp',
'Rapidus Fio': 'images/rapidus_fio.webp',
'Refectio': 'images/refectio.webp',
'Report!': 'images/report.webp',
'Rock Riot': 'images/rock_riot.webp',
'Rocket Science': 'images/rocket_science.webp',
'Rune Sword': 'images/rune_sword.webp',
'Runetracer': 'images/runetracer.webp',
'Sacred Beasts Tower Shield': 'images/sacred_beasts_tower_shield.webp',
'Salamender': 'images/salamender.webp',
'Sanctuary': 'images/sanctuary.webp',
'Santa Javelin': 'images/santa_javelin.webp',
'Santa Water': 'images/santa_water.webp',
'Science Rocks': 'images/science_rocks.webp',
'Seraphic Cry': 'images/seraphic_cry.webp',
'Shadow Pinion': 'images/shadow_pinion.webp',
'Shadow Servant': 'images/shadow_servant.webp',
'Sharp Tongue': 'images/sharp_tongue.webp',
'Short Gun': 'images/short_gun.webp',
'Shuriken': 'images/shuriken.webp',
'Silver Ring': 'images/silver_ring.webp',
'Silver Wind': 'images/silver_wind.webp',
"Skull O'Maniac": 'images/skull_o_maniac.webp',
'Sole Solution': 'images/sole_solution.webp',
'Song of Mana': 'images/song_of_mana.webp',
'Sonic Bloom': 'images/sonic_bloom.webp',
'Sonic Dash': 'images/sonic_dash.webp',
'Sonic Whip': 'images/sonic_whip.webp',
'Soul Eater': 'images/soul_eater.webp',
'Spellbinder': 'images/spellbinder.webp',
'SpellStream': 'images/spellstream.webp',
'SpellStrike': 'images/spellstrike.webp',
'SpellString': 'images/spellstring.webp',
'SpellStrom': 'images/spellstrom.webp',
'Spinach': 'images/spinach.webp',
'Spirit Tornado Tip': 'images/spirit_tornado_tip.webp',
'Spread Shot': 'images/spread_shot.webp',
'Stamazza': 'images/stamazza.webp',
'Star Flail': 'images/star_flail.webp',
'Stellar Blade': 'images/stellar_blade.webp',
'Stone Mask': 'images/stone_mask.webp',
'Summon Night': 'images/summon_night.webp',
'Tenebris Tonitrus': 'images/tenebris_tonitrus.webp',
'The RPG': 'images/the_RPG.webp',
'Thousand Edge': 'images/thousand_edge.webp',
'Thunder Loop': 'images/thunder_loop.webp',
'Thunderbolt Spear': 'images/thunderbolt_spear.webp',
'Time Warp': 'images/time_warp.webp',
'Tirajisú': 'images/tirajisu.webp',
"Torrona's Box": 'images/torronas_box.webp',
'Tri-Bracelet': 'images/tri-bracelet.webp',
'Trident': 'images/trident.webp',
'Tyrfing': 'images/tyrfing.webp',
'Umbra': 'images/umbra.webp',
'Unholy Vespers': 'images/unholy_vespers.webp',
'Universitas': 'images/universitas.webp',
'Unjust Ejection': 'images/unjust_ejection.webp',
'Valkyrie Turner': 'images/valkyrie_turner.webp',
'Vampire Killer': 'images/vampire_killer.webp',
'Vandalier': 'images/vandalier.webp',
'Vanitas Whip': 'images/vanitas_whip.webp',
'Vento Sacro': 'images/vento_sacro.webp',
'Vibhuti Whip': 'images/vibhuti_whip.webp',
'Vicious Hunger': 'images/vicious_hunger.webp',
'Victory Sword': 'images/victory_sword.webp',
'Vol Confodere': 'images/vol_confodere.webp',
'Vol Luminatio': 'images/vol_luminatio.webp',
'Vol Umbra': 'images/vol_umbra.webp',
'Wave Beam': 'images/wave_beam.webp',
"Weapon-Power-Up": 'images/weapon_power-up.webp',
'Whip': 'images/whip.webp',
'Wind Whip': 'images/wind_whip.webp',
'Wine Glass': 'images/wine_glass.webp',
'Wings': 'images/wings.webp',
'Wrecking Ball': 'images/wrecking_ball.webp',
'Yagyu Shuriken': 'images/yagyu_shuriken.webp',
};