const imageMap = {
'Acerbatus': 'images/acerbatus.webp',
'Alchemy Whip': 'images/alchemy_whip.webp',
'Alucard Shield': 'images/alucard_shield.webp',
'Alucard Spear': 'images/alucard_spear.webp',
'Alucard Swords': 'images/alucard_swords.webp',
'Alucart Sworb': 'images/alucart_sworb.webp',
'Armor': 'images/armor.webp',
'Ashes of Muspell': 'images/ashes_of_muspell.webp',
'Atmo-Torpedo': 'images/atmo_torpedo.webp',
'Attractorb': 'images/attractorb.webp',
'Aurablaster Tip': 'images/aurablaster_tip.webp',
'Axe': 'images/axe.webp',
'BFC2000-AD': 'images/BFC2000-AD.webp',
'Bi-Bracelet': 'images/bi-bracelet.webp',
'Big Fuzzy Fist': 'images/big_fuzzy_fist.webp',
'Blade Crossbow': 'images/blade_crossbow.webp',
'Bloody Tear': 'images/bloody_tear.webp',
'Boo Roo Boolle': 'images/boo_roo_boolle.webp',
'Bracelet': 'images/bracelet.webp',
'Bracer': 'images/bracer.webp',
'Bwaka Knife': 'images/bwaka_knife.webp',
'C-U-Laser': 'images/C-U-laser.webp',
'Candelabrador': 'images/candelabrador.webp',
'Celestial Voulge': 'images/celestial_voulge.webp',
'': 'images/clear_asteroids.webp',
'': 'images/clear_debris.webp',
'': 'images/clock_lancet.webp',
'': 'images/clock_tower.webp',
'': 'images/clover.webp',
'': 'images/cocytus.webp',
'': 'images/confodere.webp',
'': 'images/crimson_shroud.webp',
'': 'images/crissaegrim_tip.webp',
'': 'images/cross_crasher_tip.webp',
'': 'images/cross.webp',
'': 'images/crossed_wires.webp',
'': 'images/crown.webp',
'': 'images/curved_knife.webp',
'': 'images/dark_iron_shield.webp',
'': 'images/daybreaker_tip.webp',
'': 'images/death_spiral.webp',
'': 'images/discus.webp',
'': 'images/diver_mines.webp',
'': 'images/dragon_water_whip.webp',
'': 'images/duplicator.webp',
'': 'images/ebony_wings.webp',
'': 'images/echo_night.webp',
'': 'images/eight_the_sparrow.webp',
'': 'images/emergency_meeting.webp',
'': 'images/empty_tome.webp',
'': 'images/endo_gears.webp',
'': 'images/eskizzibur.webp',
'': 'images/festive_winds.webp',
'': 'images/fire_wand.webp',
'': 'images/fire-L3GS.webp',
'': 'images/firearm.webp',
'': 'images/flames_of_misspell.webp',
'': 'images/flash_arrow.webp',
'': 'images/four_seasons.webp',
'': 'images/fulgur.webp',
'': 'images/fuwalafuwaloo.webp',
'': 'images/gale_force.webp',
'': 'images/garlic.webp',
'': 'images/gatti_amari.webp',
'': 'images/gemma_torpor.webp',
'': 'images/glass_fandango.webp',
'': 'images/globus.webp',
'': 'images/godai_shuffle.webp',
'': 'images/gold_ring.webp',
'': 'images/gorgeous_moon.webp',
'': 'images/guardians_targe.webp',
'': 'images/gungnir_souris.webp',
'': 'images/hand_grenade.webp',
'': 'images/heaven_sword.webp',
'': 'images/hellfire.webp',
'': 'images/hex.webp',
'Hollow Heart': 'images/hollow_heart.webp',
'': 'images/holy_wand.webp',
'': 'images/homing_miss.webp',
'': 'images/hydrostormer_tip.webp',
'': 'images/ice_fang.webp',
'': 'images/impostongue.webp',
'': 'images/infinite_corridor.webp',
'': 'images/iron_ball.webp',
'': 'images/iron_shield.webp',
'': 'images/javelin.webp',
'': 'images/jet_black_whip.webp',
'': 'images/jodore.webp',
'': 'images/just_vent.webp',
"Karoma's Mana": 'images/karomas_mana.webp',
'': 'images/keremet_bubbles.webp',
'': 'images/keremet_morbus.webp',
'': 'images/king_bible.webp',
'': 'images/knife.webp',
'': 'images/la_borra.webp',
'': 'images/laurel.webp',
'': 'images/legionnaire.webp',
'': 'images/lifesign_scan.webp',
'': 'images/lightning_ring.webp',
'': 'images/long_gun.webp',
'': 'images/long_inus.webp',
'': 'images/lucky_swipe.webp',
'': 'images/luminaire.webp',
'': 'images/luminatio.webp',
'': 'images/mace.webp',
'': 'images/magic_wand.webp',
'': 'images/mannajja.webp',
'': 'images/mazo_familiar.webp',
'': 'images/meal_ticket.webp',
'': 'images/melio_confodere.webp',
'': 'images/metaglio_left.webp',
'': 'images/metaglio_right.webp',
'': 'images/metal_claw.webp',
'': 'images/mille_bolle_blu.webp',
'': 'images/millionaire.webp',
'': 'images/mini_crewmate.webp',
'': 'images/mini_engineer.webp',
'': 'images/mini_ghost.webp',
'': 'images/mini_guardian.webp',
'': 'images/mini_impostor.webp',
'': 'images/mini_scientist.webp',
'': 'images/mini_shapeshifter.webp',
'': 'images/mirage_robe.webp',
'': 'images/moon_rod.webp',
'': 'images/mormegil_tip.webp',
'': 'images/multistage_missiles.webp',
'': 'images/muramasa.webp',
'': 'images/myo_lift.webp',
'': 'images/night_sword.webp',
'': 'images/nightmare.webp',
'': 'images/nitesco.webp',
'': 'images/no_future.webp',
'': 'images/ophion.webp',
'': 'images/optical_shot.webp',
'': 'images/pako_battiliar.webp',
'': 'images/paranormal_scan.webp',
'Parm Aegis': 'images/parm_aegis.webp',
'': 'images/peachone.webp',
'': 'images/pentagram.webp',
'': 'images/peri_pendulum.webp',
'': 'images/phas3r.webp',
'': 'images/phiera_der_tuphello.webp',
'': 'images/phieraggi.webp',
'': 'images/photonstorm.webp',
'': 'images/platinum_whip.webp',
'': 'images/pneuma_tempestas.webp',
'': 'images/prism_lass.webp',
'': 'images/prismatic_missile.webp',
'': 'images/pronto_beam.webp',
'': 'images/prototype_A.webp',
'': 'images/prototype_B.webp',
'': 'images/prototype_C.webp',
'': 'images/pummarola.webp',
'': 'images/raging_fire.webp',
'': 'images/rapidus_fio.webp',
'': 'images/refectio.webp',
'': 'images/report.webp',
'': 'images/rock_riot.webp',
'': 'images/rocket_science.webp',
'': 'images/rpi_head.webp',
'': 'images/rune_sword.webp',
'': 'images/runetracer.webp',
'': 'images/sacred_beasts_tower_shield.webp',
'': 'images/salamender.webp',
'': 'images/sanctuary.webp',
'': 'images/santa_javelin.webp',
'': 'images/santa_water.webp',
'': 'images/science_rocks.webp',
'': 'images/seraphic_cry.webp',
'': 'images/shadow_pinion.webp',
'': 'images/shadow_servant.webp',
'': 'images/sharp_tongue.webp',
'': 'images/short_gun.webp',
'': 'images/shuriken.webp',
'': 'images/silver_ring.webp',
'': 'images/silver_wind.webp',
'': 'images/skull_o_maniac.webp',
'': 'images/sole_solution.webp',
'': 'images/song_of_mana.webp',
'': 'images/sonic_bloom.webp',
'': 'images/sonic_dash.webp',
'': 'images/sonic_whip.webp',
'': 'images/soul_eater.webp',
'': 'images/spellbinder.webp',
'': 'images/spellstream.webp',
'': 'images/spellstrike.webp',
'': 'images/spellstring.webp',
'': 'images/spellstrom.webp',
'': 'images/spinach.webp',
'': 'images/spirit_tornado_tip.webp',
'': 'images/spread_shot.webp',
'': 'images/stamazza.webp',
'': 'images/star_flail.webp',
'': 'images/stellar_blade.webp',
'': 'images/stone_mask.webp',
'': 'images/summon_night.webp',
'': 'images/tenebris_tonitrus.webp',
'': 'images/the_RPG.webp',
'': 'images/thousand_edge.webp',
'': 'images/thunder_loop.webp',
'': 'images/thunderbolt_spear.webp',
'': 'images/time_warp.webp',
'': 'images/tirajisu.webp',
'': 'images/torronas_box.webp',
'Tri-Bracelet': 'images/tri-bracelet.webp',
'': 'images/trident.webp',
'': 'images/tyrfing.webp',
'': 'images/umbra.webp',
'': 'images/unholy_vespers.webp',
'': 'images/universitas.webp',
'Unjust Ejection': 'images/unjust_ejection.webp',
'Valkyrie Turner': 'images/valkyrie_turner.webp',
'Vampire Killer': 'images/vampire_killer.webp',
'Vandalier': 'images/vandalier.webp',
'Vanitas Whip': 'images/vanitas_whip.webp',
'Vento Sacro': 'images/vento_sacro.webp',
'Vibhuti Whip': 'images/vibhuti_whip.webp',
'Vicious Hunger': 'images/vicious_hunger.webp',
'Victory Sword': 'images/victory_sword.webp',
'Vol Confodere': 'images/vol_confodere.webp',
'Vol Luminatio': 'images/vol_luminatio.webp',
'Vol Umbra': 'images/vol_umbra.webp',
'Wave Beam': 'images/wave_beam.webp',
'Weapon Power-Up': 'images/weapon_power-up.webp',
'Whip': 'images/whip.webp',
'Wind Whip': 'images/wind_whip.webp',
'Wine Glass': 'images/wine_glass.webp',
'Wings': 'images/wings.webp',
'Wrecking Ball': 'images/wrecking_ball.webp',
'Yagyu Shuriken': 'images/yagyu_shuriken.webp',
};